name: application
description: "A Demo exam multi App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
      # core deps

  dio: ^5.8.0+1
  uuid: ^4.5.1
  equatable: ^2.0.5
  go_router: ^15.1.2
  easy_localization: ^3.0.7+1

  # ui
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.2
  cupertino_icons: ^1.0.8
  markdown_widget: ^2.3.2+8
  # material_symbols_icons: ^4.2815.0

  # may be not needet ?...
  mobx: ^2.5.0
  flutter_mobx: ^2.3.0
  grouped_list: ^6.0.0
  
  # file deps
  file_picker: ^10.1.6
  file_selector: ^1.0.2
  path_provider: ^2.1.5
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  mobx_codegen: ^2.6.1  
  flutter_lints: ^5.0.0

dependency_overrides:
  # March 22 2024:
  # Handle flutter_test depending on meta 1.11.0 while Jinja uses 1.12.0
  meta: 1.16.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
