services:

  postgres:
    image: "postgres:17.2"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"

  # mssql:
  #   image: "mcr.microsoft.com/azure-sql-edge:latest"
  #   platform: linux/amd64
  #   ports:
  #     - "1433:1433"
  #   environment:
  #     SA_PASSWORD: "Admin12345"
  #     ACCEPT_EULA: "Y"

